name: easy_ads_flutter
description: Easy Ads is a wrapper around famous ad packages which let you integrate ads easily
version: 2.3.2
homepage: https://github.com/jpolstre/easy-ads.git
repository: https://github.com/jpolstre/easy-ads.git
publish_to: none

environment:
  sdk: ">=2.18.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^3.1.0
  collection: ^1.18.0
  # 0.3.9 da error de compilacion, si se cambia a 0.3.9 y luego volver a 0.3.8 ya no es posible abria que clonar otra vez git clone https://github.com/jpolstre/easy-ads.git
  # unity_ads_plugin: ^0.3.8
  applovin_max: ^2.5.0 #3.3.0
  easy_audience_network: ^0.0.6
  logger: ^2.0.2+1
  # flutter_ironsource_x: ^2.7.2
  flutter_ironsource_x:
    git:
      url: https://github.com/jpolstre/flutter_ironsource_x.git
  provider: ^6.0.5
  # adcolony_flutter: ^1.7.1
  # startapp_sdk: ^0.4.2

  # vungle: ^0.6.12
  # yandex_mobileads: ^1.3.0
  # my_target_flutter: ^0.1.0+3
  

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
